theme: jekyll-theme-cayman

title: Histórico do CEUE
description: Projeto independente para listar informações históricas do CEUE (Centro dos Estudantes Universitários de Engenharia) fundado em 1903, a mais antiga agremiação de estudantes em atividade no Brasil e (possivelmente) da América Latina